"""The library MMD must agree with the corrected notebook's implementation.

Two independent layers of evidence, both against the protected notebook,
which is never touched or executed:

1. `_notebook_*` below is a verbatim-behavior transcription (by hand) of
   `kernel_sums_exponential_hamming` / `compute_mmd_biased_unbiased` from
   experiments-analysis/analysis_mmd_distribution_distance_corrected.ipynb
   (code cell 11). Tiny arrays, explicit expected values.
2. `test_matches_independent_notebook_fixture` compares against
   `tests/fixtures/mmd_notebook_reference_v1/fixture.json`, which was
   generated by executing the *exact, hash-verified* notebook source block
   (see docs/MMD_NOTEBOOK_PROVENANCE.md) in an isolated namespace that never
   imports `maskeddiffusion.metrics.mmd` — an independent check that (1)'s
   hand transcription is itself faithful to the real notebook cell.
"""

import json
import math
from pathlib import Path

import pytest
import torch

from maskeddiffusion.metrics.mmd import (
    compute_mmd,
    kernel_sums_exponential_hamming,
    sqrt_clipped_mmd,
)

FIXTURE_PATH = Path(__file__).parents[1] / "fixtures" / "mmd_notebook_reference_v1" / "fixture.json"

LAMBDAS = [4.0, 8.0]


# --- notebook-behavior reference (transcribed from cell 11) -----------------


def _notebook_kernel_sums(X, Y, lambdas, chunk_size=1024):
    m, n, N_dim = X.shape[0], Y.shape[0], X.shape[1]
    sums = {lam: 0.0 for lam in lambdas}
    X = X.to(torch.float32)
    Y = Y.to(torch.float32)
    for i_start in range(0, m, chunk_size):
        X_chunk = X[i_start : i_start + chunk_size]
        for j_start in range(0, n, chunk_size):
            Y_chunk = Y[j_start : j_start + chunk_size]
            overlaps = torch.matmul(X_chunk, Y_chunk.t()) / N_dim
            norm_hamming = (1.0 - overlaps) / 2.0
            for lam in lambdas:
                sums[lam] += torch.exp(-lam * norm_hamming).sum().item()
    return sums


def _notebook_mmd(X, Y, lambdas, chunk_size=1024):
    m, n = len(X), len(Y)
    sum_xx = _notebook_kernel_sums(X, X, lambdas, chunk_size)
    sum_yy = _notebook_kernel_sums(Y, Y, lambdas, chunk_size)
    sum_xy = _notebook_kernel_sums(X, Y, lambdas, chunk_size)
    diag_xx, diag_yy = float(m), float(n)
    out = {}
    for lam in lambdas:
        mmd2_biased = sum_xx[lam] / (m * m) + sum_yy[lam] / (n * n) - 2.0 * sum_xy[lam] / (m * n)
        xx_u = (sum_xx[lam] - diag_xx) / (m * (m - 1)) if m > 1 else 0.0
        yy_u = (sum_yy[lam] - diag_yy) / (n * (n - 1)) if n > 1 else 0.0
        out[f"biased_{lam}"] = mmd2_biased
        out[f"unbiased_{lam}"] = xx_u + yy_u - 2.0 * sum_xy[lam] / (m * n)
    return out


def spins(b, n, seed):
    g = torch.Generator().manual_seed(seed)
    return torch.where(torch.rand((b, n), generator=g) < 0.5, 1.0, -1.0)


def test_library_matches_notebook_reference():
    x, y = spins(7, 10, 1), spins(5, 10, 2)
    ours = compute_mmd(x, y, LAMBDAS)
    ref = _notebook_mmd(x, y, LAMBDAS)
    for lam in LAMBDAS:
        assert ours.biased_mmd2[lam] == pytest.approx(ref[f"biased_{lam}"], rel=1e-10)
        assert ours.unbiased_mmd2_raw[lam] == pytest.approx(ref[f"unbiased_{lam}"], rel=1e-10)


def test_explicit_hand_computed_value():
    """Two 1-element sets over N=2: MMD² is exactly 2 - 2*k(x,y)."""
    x = torch.tensor([[1.0, 1.0]])
    y = torch.tensor([[1.0, -1.0]])
    # q = 0, norm_hamming = 1/2, k = exp(-lam/2)
    res = compute_mmd(x, y, [4.0])
    expected = 1.0 + 1.0 - 2.0 * math.exp(-2.0)
    # kernel entries are computed in float32 (as in the notebook)
    assert res.biased_mmd2[4.0] == pytest.approx(expected, rel=1e-6)


def test_identical_sets_zero_biased():
    x = spins(6, 8, 3)
    res = compute_mmd(x, x.clone(), LAMBDAS)
    for lam in LAMBDAS:
        assert res.biased_mmd2[lam] == pytest.approx(0.0, abs=1e-9)


def test_permutation_invariance():
    x, y = spins(6, 8, 4), spins(6, 8, 5)
    perm = torch.randperm(6, generator=torch.Generator().manual_seed(0))
    a = compute_mmd(x, y, LAMBDAS)
    b = compute_mmd(x[perm], y, LAMBDAS)
    for lam in LAMBDAS:
        # float32 accumulation order differs under permutation
        assert a.biased_mmd2[lam] == pytest.approx(b.biased_mmd2[lam], abs=1e-6)
        assert a.unbiased_mmd2_raw[lam] == pytest.approx(b.unbiased_mmd2_raw[lam], abs=1e-6)


def test_self_diagonal_handling():
    """Self-kernel diagonal is exactly 1 per row; sums must reflect it."""
    x = spins(4, 6, 6)
    sums = kernel_sums_exponential_hamming(x, x, [4.0])
    off = _notebook_kernel_sums(x, x, [4.0])[4.0] - 4.0
    assert sums[4.0] - 4.0 == pytest.approx(off, rel=1e-12)


def test_unbiased_can_be_negative_and_is_not_clipped():
    found_negative = False
    for seed in range(40):
        a, b = spins(4, 16, 100 + seed), spins(4, 16, 200 + seed)
        res = compute_mmd(a, b, [4.0])
        if res.unbiased_mmd2_raw[4.0] < 0:
            found_negative = True
            break
    assert found_negative, "expected a negative raw unbiased MMD² among same-law draws"


def test_mixture_agrees_with_weighted_components():
    x, y = spins(5, 8, 7), spins(5, 8, 8)
    res = compute_mmd(x, y, LAMBDAS, weights=[3.0, 1.0])
    expected = 0.75 * res.biased_mmd2[4.0] + 0.25 * res.biased_mmd2[8.0]
    assert res.mixture_biased_mmd2 == pytest.approx(expected, rel=1e-12)
    # uniform default
    res_u = compute_mmd(x, y, LAMBDAS)
    expected_u = 0.5 * (res_u.biased_mmd2[4.0] + res_u.biased_mmd2[8.0])
    assert res_u.mixture_biased_mmd2 == pytest.approx(expected_u, rel=1e-12)


def test_chunked_equals_unchunked():
    x, y = spins(30, 8, 9), spins(25, 8, 10)
    big = compute_mmd(x, y, LAMBDAS, chunk_size=1024)
    small = compute_mmd(x, y, LAMBDAS, chunk_size=4)
    for lam in LAMBDAS:
        # float32 accumulation order differs across chunk boundaries
        assert big.biased_mmd2[lam] == pytest.approx(small.biased_mmd2[lam], abs=1e-6)
        assert big.unbiased_mmd2_raw[lam] == pytest.approx(small.unbiased_mmd2_raw[lam], abs=1e-6)


def test_sqrt_clip_is_display_only():
    assert sqrt_clipped_mmd(-0.5) == 0.0
    assert sqrt_clipped_mmd(0.25) == 0.5


def _load_fixture():
    with open(FIXTURE_PATH) as f:
        return json.load(f)


def test_fixture_is_independent_of_production_module():
    """The fixture must record that it was generated without importing the
    package under test — otherwise it is not independent evidence."""
    fixture = _load_fixture()
    prov = fixture["provenance"]
    assert prov["notebook_sha256"] == (
        "3bc29d1904fe1444db0e5815bc4da28c4ec40b895c4889c2513d87a715b5966c"
    )
    assert "maskeddiffusion.metrics.mmd was NOT imported" in prov["generation_method"]
    assert prov["cell_index"] == 11


def test_matches_independent_notebook_fixture():
    """compute_mmd must reproduce values generated by executing the exact,
    hash-verified notebook cell block in isolation (see
    docs/MMD_NOTEBOOK_PROVENANCE.md), under both chunked and unchunked
    computation."""
    fixture = _load_fixture()
    x = torch.tensor(fixture["inputs"]["X"], dtype=torch.float32)
    y = torch.tensor(fixture["inputs"]["Y"], dtype=torch.float32)
    lambdas = fixture["inputs"]["lambdas"]
    expected = fixture["expected"]
    tol = fixture["tolerance"]

    for chunk_size in fixture["inputs"]["chunk_sizes_checked"]:
        res = compute_mmd(x, y, lambdas, chunk_size=chunk_size)
        for lam in lambdas:
            key_suffix = f"{lam:g}".replace(".", "_")
            assert res.biased_mmd2[lam] == pytest.approx(
                expected[f"mmd2_biased_lambda_{key_suffix}"], rel=tol["rel"], abs=tol["abs"]
            )
            assert res.unbiased_mmd2_raw[lam] == pytest.approx(
                expected[f"mmd2_unbiased_lambda_{key_suffix}_raw"],
                rel=tol["rel"],
                abs=tol["abs"],
            )
        assert res.mixture_biased_mmd2 == pytest.approx(
            expected["mmd2_biased_mixture"], rel=tol["rel"], abs=tol["abs"]
        )
        assert res.mixture_unbiased_mmd2_raw == pytest.approx(
            expected["mmd2_unbiased_mixture_raw"], rel=tol["rel"], abs=tol["abs"]
        )
        assert sqrt_clipped_mmd(res.mixture_biased_mmd2) == pytest.approx(
            expected["mmd_biased_mixture"], rel=tol["rel"], abs=tol["abs"]
        )


def test_full_cross_term_no_diagonal_exclusion():
    """Cross term uses all m*n pairs even when X and Y share rows."""
    x = spins(3, 6, 11)
    res = compute_mmd(x, x.clone(), [4.0])
    # unbiased with identical sets: xx_u + yy_u - 2*xy where xy INCLUDES the
    # matching pairs (k=1), driving the estimate negative
    assert res.unbiased_mmd2_raw[4.0] < 0
